import { getTranslations, setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import { Activity, FileText, Wallet, BarChart3, ArrowRight, Bell } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import type { Locale } from '@/i18n/routing';

export const revalidate = 60;

export default async function DashboardPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const tT = await getTranslations({ locale });
  setRequestLocale(locale as Locale);
  const tCommon = await getTranslations('common');

  const cards = [
    {
      href: '/dashboard/portfolio',
      icon: <Activity className="h-5 w-5 text-primary" />,
      title: tT('dashboard.portfolioAiAnalysis'),
      description: tT('dashboard.riskScoringAndUnlockImpact'),
      badge: 'Pro',
    },
    {
      href: '/dashboard/tax',
      icon: <FileText className="h-5 w-5 text-gain" />,
      title: tT('dashboard.taxReport'),
      description: tT('dashboard.autoGeneratedTaxSummary'),
      badge: 'Pro',
      onlyJa: true,
    },
    {
      href: '/dashboard/wallet',
      icon: <Wallet className="h-5 w-5 text-tier-d" />,
      title: tT('dashboard.walletIntegration'),
      description: tT('dashboard.hyperliquidHistoryBuilderFee'),
      badge: 'Connect',
    },
    {
      href: '/dashboard/alerts',
      icon: <Bell className="h-5 w-5 text-primary" />,
      title: tT('dashAlerts.alerts'),
      description: tT('dashboard.priceUnlockIdoNotifications'),
      badge: 'Free',
    },
    {
      href: '/dashboard/watchlist',
      icon: <BarChart3 className="h-5 w-5 text-gain" />,
      title: tT('dashboard.watchlist'),
      description: tT('dashboard.manageFavoriteCoins'),
      badge: 'Free',
    },
  ].filter((c) => !c.onlyJa || locale === 'ja');

  return (
    <div className="container py-4 space-y-8">
      <header>
        <h1 className="text-xl md:text-2xl font-semibold">{tCommon('siteName')} Dashboard</h1>
        <p className="text-sm text-muted-foreground mt-1">
          {tT('dashboard.aiPoweredPersonalCryptoManagement')}
        </p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {cards.map((c) => (
          <Link
            key={c.href}
            href={c.href}
            className="group rounded-lg border border-border/60 bg-card/30 p-5 space-y-3 hover:border-primary/40 hover:bg-card/50 transition-colors"
          >
            <div className="flex items-start justify-between">
              <div className="p-2.5 rounded-lg bg-muted/40">{c.icon}</div>
              <Badge variant={c.badge === 'Pro' ? 'default' : 'secondary'} className="text-[10px]">
                {c.badge}
              </Badge>
            </div>
            <div>
              <h3 className="font-semibold group-hover:text-primary transition-colors">{c.title}</h3>
              <p className="text-xs text-muted-foreground mt-1">{c.description}</p>
            </div>
            <ArrowRight className="h-4 w-4 text-muted-foreground group-hover:text-primary transition-colors" />
          </Link>
        ))}
      </div>
    </div>
  );
}
