import { getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import Image from 'next/image';
import { Link } from '@/i18n/routing';
import { Globe, FileText, Github, Twitter, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { TierBadge } from '@/components/coin/TierBadge';
import { getCoin, getCoinSummary } from '@/lib/db/queries';
import { formatPrice, formatCompact, formatPercent, formatSupply, changeColor, cn } from '@/lib/utils';
import type { Locale } from '@/i18n/routing';

export const revalidate = 600;

interface PageProps {
  params: Promise<{ locale: Locale; symbol: string }>;
}

export default async function CoinDetailPage({ params }: PageProps) {
  const { locale, symbol } = await params;
  setRequestLocale(locale);
  const t = await getTranslations('coin');
  const tCommon = await getTranslations('common');
  const tTier = await getTranslations('tier');

  const result = await getCoin(symbol);
  if (!result) notFound();

  const { coin, summary: dbSummary } = result;
  const summary = dbSummary || (await getCoinSummary(coin.id, locale));

  return (
    <div className="container py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center gap-6">
        <div className="flex items-center gap-4">
          {coin.image_url && (
            <Image src={coin.image_url} alt={coin.symbol} width={64} height={64} className="rounded-full" unoptimized />
          )}
          <div className="space-y-1">
            <div className="flex items-center gap-3 flex-wrap">
              <h1 className="text-3xl font-bold">{coin.name}</h1>
              <Badge variant="secondary" className="uppercase">{coin.symbol}</Badge>
              {coin.rank && <Badge variant="outline">#{coin.rank}</Badge>}
              <TierBadge tier={coin.tier} size="md" />
            </div>
            <p className="text-xs text-muted-foreground">{t('tierExplanation')}</p>
          </div>
        </div>
        <div className="md:ml-auto text-right space-y-1">
          <div className="text-3xl font-bold num tabular-nums">{formatPrice(coin.price_usd)}</div>
          <div className={cn('text-sm font-medium num', changeColor(coin.change_24h))}>
            {formatPercent(coin.change_24h)} (24h)
          </div>
          {coin.change_7d != null && (
            <div className={cn('text-xs num', changeColor(coin.change_7d))}>{formatPercent(coin.change_7d)} (7d)</div>
          )}
        </div>
      </div>

      {/* AI Summary (中立教育者風 LLM 生成) */}
      {summary && (
        <div className="rounded-lg border border-primary/30 bg-primary/5 p-4 space-y-2">
          <h2 className="font-semibold text-sm flex items-center gap-2">
            <span className="text-primary">{t('aiAnalysis')}</span>
            <Badge variant="secondary" className="text-[10px]">DeepSeek V4 Pro · {locale}</Badge>
          </h2>
          <p className="text-sm leading-relaxed">{summary}</p>
        </div>
      )}

      <Separator />

      {/* Key metrics */}
      <section className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <MetricCard label="Market Cap" value={formatCompact(coin.market_cap_usd)} />
        <MetricCard label={t('fullyDiluted') ?? 'FDV'} value={formatCompact(coin.fdv_usd)} />
        <MetricCard label="24h Vol" value={formatCompact(coin.volume_24h_usd)} />
        <MetricCard label="Tier Score" value={coin.tier_score ? coin.tier_score.toFixed(1) : '—'} />
        <MetricCard label="Circulating" value={formatSupply(coin.circulating_supply, coin.symbol.toUpperCase())} />
        <MetricCard label="Total Supply" value={formatSupply(coin.total_supply, coin.symbol.toUpperCase())} />
        <MetricCard
          label="Max Supply"
          value={coin.max_supply ? formatSupply(coin.max_supply, coin.symbol.toUpperCase()) : '∞'}
        />
        <MetricCard label="ATH" value={formatPrice(coin.ath_usd)} />
      </section>

      {/* 2-column: Description + Links */}
      <section className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-3">
          <h2 className="text-xl font-semibold">{t('overview')}</h2>
          {summary ? (
            <p className="text-sm leading-relaxed">{summary}</p>
          ) : (
            <p className="text-sm text-muted-foreground">
              Description coming soon — generated by Cointier AI in 7 languages.
            </p>
          )}
        </div>

        <aside className="space-y-4">
          <div className="rounded-lg border border-border/60 bg-card/30 p-4 space-y-2">
            <h3 className="font-semibold text-sm">Links</h3>
            <div className="space-y-2">
              {coin.website && <LinkRow icon={<Globe className="h-4 w-4" />} label="Website" href={coin.website} />}
              {coin.whitepaper_url && <LinkRow icon={<FileText className="h-4 w-4" />} label="Whitepaper" href={coin.whitepaper_url} />}
              {coin.github_url && <LinkRow icon={<Github className="h-4 w-4" />} label="GitHub" href={coin.github_url} />}
              {coin.twitter_url && <LinkRow icon={<Twitter className="h-4 w-4" />} label="Twitter" href={coin.twitter_url} />}
              {coin.telegram_url && <LinkRow icon={<Send className="h-4 w-4" />} label="Telegram" href={coin.telegram_url} />}
            </div>
          </div>

          {/* Buy CTA — affiliates */}
          <div className="rounded-lg border border-primary/30 bg-primary/5 p-4 space-y-3">
            <h3 className="font-semibold text-sm">{tCommon('subscribe')}</h3>
            <div className="space-y-2">
              <Button asChild className="w-full" size="sm">
                <a href={`https://bingx.com/?ref=cointier&coin=${coin.symbol}`} target="_blank" rel="noopener noreferrer">
                  {t('buyOn', { exchange: 'BingX' })}
                </a>
              </Button>
              <Button asChild variant="outline" className="w-full" size="sm">
                <a href={`https://mexc.com/?ref=cointier&coin=${coin.symbol}`} target="_blank" rel="noopener noreferrer">
                  {t('buyOn', { exchange: 'MEXC' })}
                </a>
              </Button>
            </div>
          </div>

          <div className="rounded-lg border border-border/60 bg-card/30 p-4 space-y-2">
            <h3 className="font-semibold text-sm flex items-center gap-2">
              <TierBadge tier={coin.tier} size="sm" />
              {tTier('explained')}
            </h3>
            <ul className="space-y-1.5 text-xs text-muted-foreground">
              <li>· {tTier('factors.liquidity')}</li>
              <li>· {tTier('factors.team')}</li>
              <li>· {tTier('factors.technology')}</li>
              <li>· {tTier('factors.community')}</li>
              <li>· {tTier('factors.regulatory')}</li>
              <li>· {tTier('factors.future')}</li>
            </ul>
            <p className="text-[10px] text-muted-foreground/70 pt-2">Pattern B (個人投資家向け)</p>
          </div>
        </aside>
      </section>

      <p className="text-xs text-muted-foreground pt-4">
        Data: CoinGecko, DeFiLlama, CryptoRank, DEXScreener · Tier by Cointier AI (DeepSeek V4 Pro · OpenRouter) ·{' '}
        <Link href="/" className="text-primary hover:underline">{tCommon('viewAll')}</Link>
      </p>
    </div>
  );
}

function MetricCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border/60 bg-card/30 p-3 space-y-1">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="num font-semibold tabular-nums">{value}</div>
    </div>
  );
}

function LinkRow({ icon, label, href }: { icon: React.ReactNode; label: string; href: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
    >
      {icon}
      <span>{label}</span>
    </a>
  );
}

export async function generateMetadata({ params }: PageProps) {
  const { locale, symbol } = await params;
  const result = await getCoin(symbol);
  if (!result) return { title: 'Not found' };
  const t = await getTranslations({ locale, namespace: 'metadata' });
  return {
    title: `${result.coin.name} (${result.coin.symbol.toUpperCase()})`,
    description: `${result.coin.name} — ${t('description')}`,
  };
}
